# Generated by Django 5.1.3 on 2025-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="registration_number",
        ),
        migrations.AddField(
            model_name="hospital",
            name="accreditation_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="facility_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
