# Generated by Django 5.1.3 on 2025-01-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_hospital_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="api.hospital",
            ),
        ),
    ]
