# Generated by Django 5.1.3 on 2025-01-18 21:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_gppractice_researchfield_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="initial_consultation",
        ),
        migrations.AlterModelOptions(
            name="gppractice",
            options={
                "verbose_name": "GP Practice",
                "verbose_name_plural": "GP Practices",
            },
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="priority_level",
            new_name="priority",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="booking_method",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="referral",
        ),
        migrations.AddField(
            model_name="appointment",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.gppractice",
            ),
        ),
        migrations.AddField(
            model_name="generalpractitioner",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalpractitioner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalpractitioner",
            name="qualification",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalpractitioner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="generalpractitioner",
            name="years_of_experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gppractice",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gppractice",
            name="opening_hours",
            field=models.JSONField(
                default={}, help_text="Store opening hours for each day"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gppractice",
            name="postcode",
            field=models.CharField(default="00000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientgpregistration",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_gp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_patients",
                to="api.generalpractitioner",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="gp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="api.generalpractitioner",
            ),
        ),
        migrations.AlterField(
            model_name="generalpractitioner",
            name="availability_schedule",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="generalpractitioner",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gp_doctors",
                to="api.gppractice",
            ),
        ),
        migrations.AlterField(
            model_name="generalpractitioner",
            name="specializations",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="gppractice",
            name="capacity",
            field=models.IntegerField(
                help_text="Maximum number of registered patients"
            ),
        ),
        migrations.AlterField(
            model_name="patientgpregistration",
            name="gp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to="api.generalpractitioner",
            ),
        ),
        migrations.AlterField(
            model_name="patientgpregistration",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gp_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientgpregistration",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_patients",
                to="api.gppractice",
            ),
        ),
        migrations.AlterField(
            model_name="patientgpregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "Pending"),
                    ("TRANSFERRED", "Transferred"),
                    ("INACTIVE", "Inactive"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_gp_practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_patients",
                to="api.gppractice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientgpregistration",
            unique_together={("patient", "practice", "status")},
        ),
        migrations.DeleteModel(
            name="InitialConsultation",
        ),
    ]
