# Generated by Django 5.1.3 on 2025-01-19 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_appointment_initial_consultation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_date"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="actual_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900),
                help_text="Expected duration of appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "status"],
                name="api_appoint_appoint_0fe7ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="api_appoint_patient_561ffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["practice", "appointment_date"],
                name="api_appoint_practic_f09d87_idx",
            ),
        ),
    ]
